### ISSUE TITLE
TicTacToe | Minimax bot skips some obvious states after alpha beta pruning implementation

### ISSUE THREAD

**Issue by linonymous** [linonymous/Intermediate_Python#6]
with alpha beta pruning implementation
```
_ _ _
_ _ _
_ _ _

Enter move for player swpanilrow and column
row:2
col:0
2 0

_ _ _
_ _ _
O _ _

Let JARVIS play....
0 0

X _ _
_ _ _
O _ _

Enter move for player swpanilrow and column
row:0
col:2
0 2

X _ O
_ _ _
O _ _

Let JARVIS play....
0 1

X X O
_ _ _
O _ _

Enter move for player swpanilrow and column
row:
```

after checking out the commit before alpha beta pruning
```
Welcome swapnil!! you will play against JARVIS!
Lets start the game...

_ _ _
_ _ _
_ _ _

Enter move for player swapnilrow and column
row:2
col:0
2 0

_ _ _
_ _ _
O _ _

Let JARVIS play....
1 1

_ _ _
_ X _
O _ _

Enter move for player swapnilrow and column
row:
```

**Comment by bhosalems** [comment]
Creating pull request https://github.com/linonymous/Intermediate_Python/pull/7

**Comment by linonymous** [comment]
Will review it! (y)

**Comment by bhosalems** [comment]
We can optimize further by taking these cells as set in python while we are moving over each cell in min-max. Just check above pull request and then we can discuss more about optimizing further.

**Comment by linonymous** [comment]
Yup, let me understand this first. What was the wrong happening there?

**Comment by linonymous** [comment]
Merged the pull request, will verify the case and close the issue.
